name: tc_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - bottleneck
  - dask
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - pip:
    - -r requirements-dev.txt
  - tensorflow
  - xarray

