name: tc_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - basemap
  - bottleneck
  - bayesian-optimization
  - dask
  - keras-tuner
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
  - papermill
  - tensorflow-gpu=2.4.1
  - xarray

